import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

[font]
size = 10
normal = { family = "MesloLGS Nerd Font Propo", style = "Regular" }
bold = { family = "MesloLGS Nerd Font Propo", style = "Bold" }
italic = { family = "MesloLGS Nerd Font Propo", style = "Italic" }
bold_italic = { family = "MesloLGS Nerd Font Propo", style = "Bold Italic" }

[env]
TERM = "xterm-256color"

[scrolling]
history = 5000

[window]
dynamic_padding = true
opacity = 0.9
title = "Alacritty"
# startup_mode = "Maximized"
dimensions = { columns = 110, lines = 30 }

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 6
